### ISSUE TITLE
Implement and test binary and binary inverse threshold

### ISSUE THREAD

**Issue by miralshah365** [BoostGSoC19/gil-miral#2]
*Two variant of Binary threshold Implemented*
1. **Simple Binary Threshold**-
If the pixel value is more than the threshold then the pixel value is set to maximum or else to 0
2. **Inverse Binary Threshold**
If the pixel value is more than the threshold then the pixel value is set to 0 or else to maximum

**Comment by mloskot** [comment]
Good job!
